### ISSUE TITLE
Error downloading events for missing id 

### ISSUE THREAD

**Issue by LucaGiamminonni** [openaire/broker-cmdline-client#4]
Downloading events when the response you get from the broker is

```
{
   "id": null,
   "completed": true,
   "values": []
}
```

then the BrokerClient.writeEvents (URL, String, Writer) method fails on the line

`url = baseUrl + "/scroll/notifications/" + data.get("id").getAsString()`

because data.get ("id") returns an instance of the JsonNull class that doesn't support the getAsString() method:

```
java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179) ~[gson-2.9.0.jar:?]
	at eu.dnetlib.broker.BrokerClient.writeEvents(BrokerClient.java:113) ~[broker-client-1.1.1.jar:1.1.1]
	at eu.dnetlib.broker.BrokerClient.downloadEvents(BrokerClient.java:83) ~[broker-client-1.1.1.jar:1.1.1]
```

**Comment by LucaGiamminonni** [comment]
I'm working to solve the problem. I will create a PR shortly.

**Comment by LucaGiamminonni** [comment]
PR created: https://github.com/openaire/broker-cmdline-client/pull/5

**Comment by micheleartini** [comment]
If the response contains 0 events, the returned object should be:
```
{
  'id': null,
  'completed': true,
  'value' : []
 }

```  
I'm not sure if also the last scroll page returns a null id, but surely your PR resolves the problem with null IDs.

**Comment by micheleartini** [comment]
I accepetd the PR, a new release will be deployed ASAP

**Comment by LucaGiamminonni** [comment]
Hi @micheleartini, thanks. From what I have seen trying the BrokerClient the response with id null is obtained both with 0 events and in the last scroll page.
